# Generated by Django 4.1.9 on 2023-06-07 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeforcesUser',
            fields=[
                ('handle', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('vkId', models.CharField(blank=True, max_length=255)),
                ('openId', models.CharField(blank=True, max_length=255)),
                ('firstName', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('contribution', models.IntegerField()),
                ('rank', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('maxRank', models.CharField(max_length=255)),
                ('maxRating', models.IntegerField()),
                ('lastOnlineTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrationTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('friendOfCount', models.IntegerField()),
                ('avatar', models.URLField()),
                ('titlePhoto', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
