# Generated by Django 4.1.9 on 2023-06-07 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeforcesuser',
            name='email',
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='avatar',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='contribution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='friendOfCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='maxRating',
            field=models.IntegerField(default='800'),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='rating',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='codeforcesuser',
            name='titlePhoto',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('originalLocale', models.CharField(max_length=255)),
                ('creationTimeSeconds', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('locale', models.CharField(max_length=255)),
                ('modificationTimeSeconds', models.DateTimeField(auto_now=True)),
                ('allowViewHistory', models.BooleanField()),
                ('tags', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('authorHandle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.codeforcesuser')),
            ],
        ),
    ]
