# Generated by Django 4.1.9 on 2023-06-07 14:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_remove_codeforcesuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentry',
            options={'ordering': ['id'], 'verbose_name': 'BlogEntry', 'verbose_name_plural': 'BlogEntries'},
        ),
        migrations.AlterModelOptions(
            name='codeforcesuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('creationTimeSeconds', models.DateTimeField(default=django.utils.timezone.now)),
                ('locale', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('parentCommentId', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('commentatorHandle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.codeforcesuser')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-creationTimeSeconds'],
            },
        ),
    ]
