# Generated by Django 4.1.9 on 2023-06-07 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_alter_blogentry_options_alter_codeforcesuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSeconds', models.DateTimeField(default=django.utils.timezone.now)),
                ('blogEntryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.blogentry')),
                ('commentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.comment')),
            ],
            options={
                'verbose_name': 'Recent Action',
                'verbose_name_plural': 'Recent Actions',
            },
        ),
    ]
