# Generated by Django 4.1.9 on 2023-06-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_recentaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recentaction',
            constraint=models.UniqueConstraint(fields=('blogEntryId', 'commentId'), name='unique_recent_action'),
        ),
    ]
