# Generated by Django 4.1.9 on 2023-06-07 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_recentaction_unique_recent_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingChange',
            fields=[
                ('contestId', models.IntegerField(primary_key=True, serialize=False)),
                ('contestName', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('ratingUpdateTimeSeconds', models.DateTimeField(default=django.utils.timezone.now)),
                ('oldRating', models.IntegerField()),
                ('newRating', models.IntegerField()),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.codeforcesuser')),
            ],
            options={
                'verbose_name': 'Rating Change',
                'verbose_name_plural': 'Rating Changes',
            },
        ),
    ]
