# Generated by Django 4.1.9 on 2023-06-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_ratingchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CF', 'Codeforces'), ('IOI', 'IOI'), ('ICPC', 'ICPC')], max_length=10)),
                ('phase', models.CharField(choices=[('BEFORE', 'Before'), ('CODING', 'Coding'), ('PENDING_SYSTEM_TEST', 'Pending System Test'), ('SYSTEM_TEST', 'System Test'), ('FINISHED', 'Finished')], max_length=20)),
                ('frozen', models.BooleanField()),
                ('durationSeconds', models.IntegerField()),
                ('startTimeSeconds', models.IntegerField(blank=True, null=True)),
                ('relativeTimeSeconds', models.IntegerField(blank=True, null=True)),
                ('websiteUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, max_length=255, null=True)),
                ('icpcRegion', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.CharField(blank=True, max_length=255, null=True)),
                ('preparedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.codeforcesuser')),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
            },
        ),
    ]
