# Generated by Django 4.1.9 on 2023-06-07 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='difficulty',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
