# Generated by Django 4.1.9 on 2023-06-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_alter_contest_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemsetName', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('index', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PROGRAMMING', 'Programming'), ('QUESTION', 'Question')], max_length=20)),
                ('points', models.FloatField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('contestId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.contest')),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
                'unique_together': {('contestId', 'index')},
            },
        ),
    ]
