# Generated by Django 4.1.9 on 2023-06-07 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeforcesuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='ProblemStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solvedCount', models.IntegerField()),
                ('contestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='Backend.problem')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.problem')),
            ],
            options={
                'verbose_name': 'Problem Statistics',
                'verbose_name_plural': 'Problem Statistics',
                'unique_together': {('contestId', 'index')},
            },
        ),
    ]
