# Generated by Django 4.1.9 on 2023-06-09 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_codeforcesuser_email_problemstatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='blogentry',
            name='tags',
        ),
        migrations.AlterField(
            model_name='comment',
            name='creationTimeSeconds',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parentCommentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.comment'),
        ),
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Backend.blogentry')),
                ('tag', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'unique_together': {('id', 'tag')},
            },
        ),
    ]
