# Generated by Django 4.1.9 on 2023-06-09 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_remove_contest_preparedby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('handle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Backend.codeforcesuser')),
                ('member', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('contestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Backend.contest')),
                ('participantType', models.CharField(choices=[('CONTESTANT', 'Contestant'), ('PRACTICE', 'Practice'), ('VIRTUAL', 'Virtual'), ('MANAGER', 'Manager'), ('OUT_OF_COMPETITION', 'Out of Competition')], max_length=20)),
                ('teamId', models.IntegerField(blank=True, null=True)),
                ('teamName', models.CharField(blank=True, max_length=255, null=True)),
                ('ghost', models.BooleanField()),
                ('room', models.IntegerField(blank=True, null=True)),
                ('startTimeSeconds', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.party')),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.member')),
            ],
        ),
        migrations.AddConstraint(
            model_name='partymember',
            constraint=models.UniqueConstraint(fields=('contestId', 'handle'), name='unique_party_member'),
        ),
    ]
